# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Samyuktha!"

In [2]:
s.split()

['Hi', 'there', 'Samyuktha!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
print("An array of 10 zeros:", np.zeros(10))

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
print("An array of 10 fives:", np.ones(10)*5)

An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
print("An array of all the even integers from 20 to 35: " , np.arange(20,35,2))

An array of all the even integers from 20 to 35:  [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
print(np.arange(0, 9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)
np.concatenate([a, b])

[5 7 9]


array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data = {'Name': ['Abisha', 'Guvishii', 'Prakash'],
        'Age': [19, 20, 21]}
df = pd.DataFrame(data)
df

Name  Age
0    Abisha   19
1  Guvishii   20
2   Prakash   21

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
import datetime
start_date = datetime.datetime(2023, 1, 1)

print("The original date is : " + str(start_date))
K = 10
res = [start_date + datetime.timedelta(days=idx) for idx in range(K)]
print("Next K dates list : " + str(res))


The original date is : 2023-01-01 00:00:00
Next K dates list : [datetime.datetime(2023, 1, 1, 0, 0), datetime.datetime(2023, 1, 2, 0, 0), datetime.datetime(2023, 1, 3, 0, 0), datetime.datetime(2023, 1, 4, 0, 0), datetime.datetime(2023, 1, 5, 0, 0), datetime.datetime(2023, 1, 6, 0, 0), datetime.datetime(2023, 1, 7, 0, 0), datetime.datetime(2023, 1, 8, 0, 0), datetime.datetime(2023, 1, 9, 0, 0), datetime.datetime(2023, 1, 10, 0, 0)]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
df2 = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age']) 
print(df2)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
